apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service-deployment
spec:
  selector:
    matchLabels:
      app: api-gateway-service
  template:
    metadata:
      labels:
        app: api-gateway-service
    spec:
      containers:
      - name: api-gateway-service
        image: sssb4/api_gateway_service
        env:
        - name: AzureKeyVault__VaultName
          valueFrom:
            configMapKeyRef:
              name: api-gateway-service-config
              key: azure_vault_name
        - name: AzureKeyVault__ClientId
          valueFrom:
            configMapKeyRef:
              name: api-gateway-service-config
              key: azure_vault_clientid
        - name: AzureKeyVault__TenantId
          valueFrom:
            configMapKeyRef:
              name: api-gateway-service-config
              key: azure_vault_tenantId
        - name: AzureKeyVault__ClientSecret
          valueFrom:
            secretKeyRef:
              name: api-gateway-service-secret
              key: azure_vault_client_secret
        - name: JWTKey
          valueFrom:
            secretKeyRef:
              name: api-gateway-service-secret
              key: jwtkey
        resources:
          limits:
            memory: "512Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  selector:
    app: api-gateway-service
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-service-config
data:
  azure_vault_name: kwetter-dev-westeu-001
  azure_vault_clientid: 54e1ce92-fb15-4d78-910d-b7af13cb97d8
  azure_vault_tenantId: 1b3ddc11-68a8-4637-896f-4c1d2536732c
  broker_host: messaging-broker


---

apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-service-secret
type: Opaque
data:
  azure_vault_client_secret: ZVZHOFF+SklOTFFNTi1GdH50N2g2VXY1RXNIcDR6YlY1NmNIbWEzWg==
  jwtkey: Rm9yVGhlTG92ZU9mVGhlR29kU3RvcmVBbmRMb2FkVGhpc1NlY3VyZWx5

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hoa-api-gateway-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway-service-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70