apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gatway-service-deployment
spec:
  selector:
    matchLabels:
      app: api-gatway-service
  template:
    metadata:
      labels:
        app: api-gatway-service
    spec:
      containers:
      - name: api-gatway-service
        image: sssb4/api_gateway_service
        env:
        - name: AzureKeyVault__VaultName
          valueFrom:
            configMapKeyRef:
              name: api-gatway-service-config
              key: azure_vault_name
        - name: AzureKeyVault__ClientId
          valueFrom:
            configMapKeyRef:
              name: api-gatway-service-config
              key: azure_vault_clientid
        - name: AzureKeyVault__TenantId
          valueFrom:
            configMapKeyRef:
              name: api-gatway-service-config
              key: azure_vault_tenantId
        - name: AzureKeyVault__ClientSecret
          valueFrom:
            secretKeyRef:
              name: api-gatway-service-secret
              key: azure_vault_client_secret
        - name: JWTKey
          valueFrom:
            secretKeyRef:
              name: api-gatway-service-secret
              key: jwtkey
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: api-gatway-service
spec:
  selector:
    app: api-gatway-service
  ports:
  - port: 8080
    targetPort: 8080


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gatway-service-config
data:
  azure_vault_name: kwetter-dev-westeu-001
  azure_vault_clientid: 54e1ce92-fb15-4d78-910d-b7af13cb97d8
  azure_vault_tenantId: 1b3ddc11-68a8-4637-896f-4c1d2536732c
  broker_host: messaging-broker


---

apiVersion: v1
kind: Secret
metadata:
  name: api-gatway-service-secret
type: Opaque
data:
  azure_vault_client_secret: ZVZHOFF+SklOTFFNTi1GdH50N2g2VXY1RXNIcDR6YlY1NmNIbWEzWg==
  jwtkey: Rm9yVGhlTG92ZU9mVGhlR29kU3RvcmVBbmRMb2FkVGhpc1NlY3VyZWx5
