apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: identity-service-db
spec:
  serviceName: "identity-service-db"
  replicas: 1  
  selector:
    matchLabels:
      app: identity-service-db
  template:
    metadata:
      labels:
        app: identity-service-db
    spec:
      containers:
      - name: identity-service-db
        image: postgres:16
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: identity-service-db-config
              key: schema
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: identity-service-db-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: identity-service-db-secret
              key: password
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: identity-service-db-pvc
          mountPath: /var/lib/postgresql/data 
  volumeClaimTemplates:
  - metadata:
      name: identity-service-db-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"  
      resources:
        requests:
          storage: 1Gi 

---

apiVersion: v1
kind: Service
metadata:
  name: identity-service-db
spec:
  selector:
    app: identity-service-db
  ports:
  - port: 5432
    targetPort: 5432


---

apiVersion: v1
kind: Secret
metadata:
  name: identity-service-db-secret
type: Opaque
data:
  username: cm9vdA==
  password: cm9vdA==

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-service-db-config
data:
  schema: profileservice



