apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service-deployment
spec:
  selector:
    matchLabels:
      app: profile-service
  template:
    metadata:
      labels:
        app: profile-service
    spec:
      containers:
      - name: profile-service
        image: sssb4/profile_service
        env:
        - name: AzureKeyVault__VaultName
          valueFrom:
            configMapKeyRef:
              name: profile-service-config
              key: azure_vault_name
        - name: AzureKeyVault__ClientId
          valueFrom:
            configMapKeyRef:
              name: profile-service-config
              key: azure_vault_clientid
        - name: AzureKeyVault__TenantId
          valueFrom:
            configMapKeyRef:
              name: profile-service-config
              key: azure_vault_tenantId
        - name: AzureKeyVault__ClientSecret
          valueFrom:
            secretKeyRef:
              name: profile-service-secret
              key: azure_vault_client_secret
        - name: ConnectionStrings__url
          valueFrom:
            secretKeyRef:
              name: profile-service-secret
              key: db_connection_string
        - name: Broker__host
          valueFrom:
            configMapKeyRef:
              name: profile-service-config
              key: broker_host
        - name: Broker__Password
          valueFrom:
            secretKeyRef:
              name: profile-service-secret
              key: broker_password
        - name: Broker__Username
          valueFrom:
            secretKeyRef:
              name: profile-service-secret
              key: broker_username
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: profile-service
spec:
  selector:
    app: profile-service
  ports:
  - port: 8080
    targetPort: 8080


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: profile-service-config
data:
  azure_vault_name: kwetter-dev-westeu-001
  azure_vault_clientid: 54e1ce92-fb15-4d78-910d-b7af13cb97d8
  azure_vault_tenantId: 1b3ddc11-68a8-4637-896f-4c1d2536732c
  broker_host: messaging-broker


---

apiVersion: v1
kind: Secret
metadata:
  name: profile-service-secret
type: Opaque
data:
  azure_vault_client_secret: ZVZHOFF+SklOTFFNTi1GdH50N2g2VXY1RXNIcDR6YlY1NmNIbWEzWg==
  db_connection_string: U2VydmVyPXByb2ZpbGUtc2VydmljZS1kYjtQb3J0PTU0MzI7RGF0YWJhc2U9cHJvZmlsZXNlcnZpY2U7VXNlcm5hbWU9cm9vdDtQYXNzd29yZD1yb290
  broker_password: Z3Vlc3QK
  broker_username: Z3Vlc3QK

