
name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - development

jobs: 
  analysis:
   runs-on: self-hosted
   steps:
      - name: Set up Azure Key Vault secrets
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # Authenticate with Azure using service principal credentials
        
      - name: Fetch secrets from Azure Key Vault
        uses: Azure/get-keyvault-secrets@v1
        with:
         keyvault: ${{ secrets.KEY_VAULT }}
        id: getSecerts
            
      - name: Analysis identity_service
        run: |
          cd identity_service
          dotnet sonarscanner begin /k:"identity_service" /d:sonar.host.url="${{  steps.getSecerts.outputs.SONAR-HOST }}"  /d:sonar.login=${{ steps.getSecerts.outputs.SONAR-IDENTITY-SERVICE-TOKEN }}
          dotnet build
          dotnet sonarscanner end /d:sonar.login=${{ steps.getSecerts.outputs.SONAR-IDENTITY-SERVICE-TOKEN }}

      
