name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: false
      DOTNET_VERSION: 8.0.x
      NODEJS_VERSION: 17
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v12
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
        
      - name: Build identity_service
        run: |
          cd identity_service
          dotnet restore "identity_service.sln"
          dotnet build
      
      - name: Build profile_service
        run: |
          cd profile_service
          dotnet restore "profile_service.sln"
          dotnet build 

      - name: Build api_gateway
        run: |
          cd api_gateway
          dotnet restore "api_gateway.sln"
          dotnet build 
            
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '${{ env.NODEJS_VERSION }}'

      - name: Build frontend
        run: |
            cd frontend
            npm install
            npm run build --if-present
 
  analysis:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Analysis identity_service
        run: |
          cd identity_service
          dotnet sonarscanner begin /k:"identity_service" /d:sonar.host.url="http://localhost:9000"  /d:sonar.login=${{ secrets.SONAR_IDENTITY_SERVICE_TOKEN }}
          dotnet build
          dotnet sonarscanner end /d:sonar.login=${{ secrets.SONAR_IDENTITY_SERVICE_TOKEN }}

      - name: Analysis profile_service
        run: |
          cd profile_service
          dotnet sonarscanner begin /k:"profile_service" /d:sonar.host.url="http://localhost:9000"  /d:sonar.login="${{ secrets.SONAR_PROFILE_SERVICE_TOKEN }}"
          dotnet build
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_PROFILE_SERVICE_TOKEN }}"


  ui-test:
    runs-on: ubuntu-latest
    needs: analysis
    env:
      CI: false
      NODEJS_VERSION: 17
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '${{ env.NODEJS_VERSION }}'

      - name: test ui
        run: |
          cd frontend
          npm install
          npx cypress run
