
name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - development

jobs: 
  analysis:
   runs-on: self-hosted
   steps:
      - name: Set up Azure Key Vault secrets
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # Authenticate with Azure using service principal credentials
        
      - name: Fetch secrets from Azure Key Vault
        uses: Azure/get-keyvault-secrets@v1.0
        with:
          keyvault: "{{secerts.KEY_VAULT}}"        # Specify the name of your Azure Key Vault
          secrets: |
            SONAR-IDENTITY-SERVICE-TOKEN
            SONAR-PROFILE-SERVICE-TOKEN
            SONAR-HOST
      - name: Analysis identity_service
        run: |
          cd identity_service
          dotnet sonarscanner begin /k:"identity_service" /d:sonar.host.url="${{ secrets.SONAR-HOST }}"  /d:sonar.login=${{ secrets.SONAR-IDENTITY-SERVICE-TOKEN }}
          dotnet build
          dotnet sonarscanner end /d:sonar.login=${{ secrets.SONAR-IDENTITY-SERVICE-TOKEN }}

      - name: Analysis profile_service
        run: |
          cd profile_service
          dotnet sonarscanner begin /k:"profile_service" /d:sonar.host.url="${{ secrets.SONAR-HOST }}"  /d:sonar.login="${{ secrets.SONAR-PROFILE-SERVICE-TOKEN }}"
          dotnet build
          dotnet son
