name: CI Pipeline

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  ui-test:
    runs-on: self-hosted
    env:
      CI: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '${{ env.NODEJS_VERSION }}'
      - name: Setting up the backend
      - uses: hoverkraft-tech/compose-action@v0.0.0
      
      - name: test ui
        run: |
          cd frontend
          npm install
          npm run
          npx cypress run
