name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - staging

jobs:
 ui-test:
    runs-on: ubuntu-latest

    env:
      CI: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '${{ env.NODEJS_VERSION }}'

      - name: Setting up the backend
        uses: hoverkraft-tech/compose-action@v2.0.0

      - name: Wait for 120 seconds
        run: sleep 120
      
      - name: test ui
        run: |
          cd frontend
          npm install
          npx cypress run
