name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - development

jobs: 
  analysis:
   runs-on: self-hosted
   steps:
      - name: Set up Azure Key Vault secrets
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
        
      - name: Fetch secrets from Azure Key Vault
        uses: Azure/get-keyvault-secrets@v1.0
        with:
          keyvault: "{{secerts.KEY_VAULT}}"        # Specify the name of your Azure Key Vault
          secrets: |
            SONAR-IDENTITY-SERVICE-TOKEN
            SONAR-PROFILE-SERVICE-TOKEN
            SONAR-HOST
