name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up .NET core SDK
      uses: actions/setup-dotnet@v4.0.0
      with:
         dotnet-version: 8.x

    - name: docker login
      run: docker login --username `${{secrets.DOCKER_LOGIN}}` --password `${{secrets.DOCKER_PASSWORD}}`
    
    - name: tag services docker images
      run: |
        docker tag api-gateway-service:'${{github.sha}}' `${{secrets.DOCKER_LOGIN}}`/api-gateway-service:'${{github.sha}}'
        docker tag tweet-service:'${{github.sha}}' `${{secrets.DOCKER_LOGIN}}`/tweet-service:'${{github.sha}}'
        docker tag profile-service:'${{github.sha}}' `${{secrets.DOCKER_LOGIN}}`/profile-service:'${{github.sha}}'
        docker tag identity-service:'${{github.sha}}' `${{secrets.DOCKER_LOGIN}}`/identity-service:'${{github.sha}}'

    - name: tag services docker images
      run: |
        docker push  `${{secrets.DOCKER_LOGIN}}`/api-gateway-service:'${{github.sha}}'
        docker push `${{secrets.DOCKER_LOGIN}}`/tweet-service:'${{github.sha}}'
        docker push `${{secrets.DOCKER_LOGIN}}`/profile-service:'${{github.sha}}'
        docker push `${{secrets.DOCKER_LOGIN}}`/identity-service:'${{github.sha}}'
