name: CD pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up .NET core SDK
      uses: actions/setup-dotnet@v4.0.0
      with:
         dotnet-version: 8.x

    - name: Build identity_service
      run: |
          cd identity_service
          dotnet restore "identity_service.sln"
          dotnet build -c release
          docker build -t identity-service:'${{github.sha}}' .
      
    - name: Build profile_service
      run: |
          cd profile_service
          dotnet restore "profile_service.sln"
          dotnet build -c release
          docker build -t profile-service:'${{github.sha}}' .
          
    - name: Build tweet_service
      run: |
          cd Tweet_service
          dotnet restore "Tweet_service.sln"
          dotnet build -c release
          docker build -t tweet-service:'${{github.sha}}' .


    - name: Build api_gateway
      run: |
          cd api_gateway
          dotnet restore "api_gateway.sln"
          dotnet build -c release
          docker build -t api-gateway-service:'${{github.sha}}' .

    - name: docker login
      uses: docker/login-action@v3.1.0
      with:
        username: ${{secrets.DOCKER_LOGIN}}
        password: ${{secrets.DOCKER_PASSWORD}}

    
    - name: tag services docker images
      run: |
        docker tag api-gateway-service:'${{github.sha}}' ${{secrets.DOCKER_LOGIN}}/api-gateway-service:'${{github.sha}}'
        docker tag tweet-service:'${{github.sha}}' ${{secrets.DOCKER_LOGIN}}/tweet-service:'${{github.sha}}'
        docker tag profile-service:'${{github.sha}}' ${{secrets.DOCKER_LOGIN}}/profile-service:'${{github.sha}}'
        docker tag identity-service:'${{github.sha}}' ${{secrets.DOCKER_LOGIN}}/identity-service:'${{github.sha}}'

    - name: tag services docker images
      run: |
        docker push ${{secrets.DOCKER_LOGIN}}/api-gateway-service:'${{github.sha}}'
        docker push ${{secrets.DOCKER_LOGIN}}/tweet-service:'${{github.sha}}'
        docker push ${{secrets.DOCKER_LOGIN}}/profile-service:'${{github.sha}}'
        docker push ${{secrets.DOCKER_LOGIN}}/identity-service:'${{github.sha}}'
