name: CD pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up .NET core SDK
      uses: actions/setup-dotnet@v4.0.0
      with:
         dotnet-version: 8.x
         
    - name: docker login
      uses: docker/login-action@v3.1.0
      with:
        username: ${{secrets.DOCKER_LOGIN}}
        password: ${{secrets.DOCKER_PASSWORD}}
        
    - name: Build and push identity_service image
      run: |
          cd identity_service
          docker build -t identity-service .
          docker tag identity-service kwetter/identity-service:latest
          docker push identity-service
      
    - name: Build and push profile_service
      run: |
          cd profile_service
          docker build -t profile-service .
          docker tag profile-service kwetter/profile-service:latest
          docker push profile-service
          
    - name: Build and push tweet_service image
      run: |
          cd Tweet_service
          docker build -t tweet-service .
          docker tag tweet-service kwetter/tweet-service:latest
          docker push tweet-service 


    - name: Build and push api_gateway image
      run: |
          cd api_gateway
          docker build -t api-gateway-service .
          docker tag api-gateway-service kwetter/api-gateway-service:latest
          docker push api-gateway-service
          
    - name: Build and push frontend iamge
      run: |
          cd frontend
          docker build -t frontend .
          docker tag frontend kwetter/frontend:latest
          docker push frontend
        
